version: "3.9"

services:
  # 🌐 Frontend estático (por ex. página de configuração BLE)
  web_ble_config:
    image: nginx:alpine
    container_name: web_ble_config
    volumes:
      - ./web_config:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    restart: always
    networks:
      - iot_net

  # 🐶 Watchdog para monitorizar/recuperar containers
  watchdog:
    build:
      context: ./watchdog
      dockerfile: Dockerfile
    container_name: gateway_iot_watchdog
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      - iot_net

  # ⏱️ Worker de agendamentos de irrigação (loop contínuo)
  cron_worker:
    build:
      context: .
      dockerfile: cron_worker/Dockerfile.cron
    container_name: cron_worker
    restart: unless-stopped
    env_file:
      - ./cron_worker/.env         # cria este ficheiro com RAILS_API_URL, API_TOKEN, DATABASE_URL, MQTT_BROKER, MQTT_PORT, TZ
    networks:
      - iot_net
    # Broker é EXTERNO (ex.: 13.48.48.4) → sem depends_on

networks:
  iot_net:
    driver: bridge
